name: whisper-recognition
services:
  web:
    container_name: whisper-web
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - whisper_data:/data
      - whisper_cache:/root/.cache/whisper
    env_file:
      - .env
    restart: unless-stopped

volumes:
  whisper_data:
    name: whisper_data
  whisper_cache:
    name: whisper_cache 